#!/bin/sh -e
# Copyright (C) 2022 Fabian Mastenbroek.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

case "$1" in
    purge)
        rm -rf /var/cache/udm-iptv
        
        # Clean up persistent installation files
        # Only remove the symlink, not the persistent config (user may have modified it)
        if [ -L /etc/udm-iptv.conf ]; then
            rm -f /etc/udm-iptv.conf
        fi
        
        # Remove boot script from on_boot.d (works for both v1 and v2+)
        for persist_root in /data /mnt/data; do
            if [ -d "$persist_root/on_boot.d" ]; then
                rm -f "$persist_root/on_boot.d/11-udm-iptv.sh"
            fi
            
            # Note: We do NOT remove /data/udm-iptv or /mnt/data/udm-iptv
            # to preserve user's persistent configuration and settings.
            # Users can manually remove it if desired.
        done
        
        if [ -e /usr/share/debconf/confmodule ]
        then
                # Source debconf library and purge db
                . /usr/share/debconf/confmodule
                db_purge
        fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0